[package]
name = "nrp"
description = "(Name Rust Program) creates a name for your application from a short description"
version = "0.1.0"
authors = ["Julio Biason <julio.biason@pm.me>"]
edition = "2018"

[dependencies]
clap = "2.33"
