[adjectives]
a = ["abounding"]
c = ["condensed"]
g = ["gaga", "galactic", "galiant", "galvanic", "gargantuan", "gaunt", "gemmed", "genial", "gentle", "geodesic", "geodesical", "ghoulish", "giant", "giddy", "gifted", "gigantic", "glamorous", "gloomy", "gnarled", "godlike", "golden", "gooey", "goofy", "gorgeous", "graceful", "grizzly", "groovy"]
j = ["jagged", "jammed", "jaunty", "jealous", "jerky", "jesting", "jinxed", "jocose", "joking", "jovial", "jubilant", "juicy", "jurassic", "justified", "juvenile"]
n = ["negative", "normative"]
p = ["popular", "potent", "pretty"]
r = ["radioactive", "random", "reactive", "robust"]
s = ["silent", "silly", "stupid"]
t = ["tacit", "thrifty", "timeless"]
w = ["wiggly"]

[metals]
a = ["actinium", "aluminium", "americium", "antimony", "arsenic", "astatine"]
b = ["barium", "berkelium", "beryllium", "bismuth", "bohrium", "boron"]
c = ["cadmium", "caesium", "calcium", "californium", "cerium", "chromium", "cobalt", "copper", "curium"]
d = ["dubnium", "duralim", "dysprosium"]
e = ["einsteinium", "erbium", "europium"]
f = ["fermium", "fernico", "francium"]
g = ["gadolinium", "gallium", "germanium", "gold"]
h = ["hafnium", "hassium", "holmium", "hydrargyrum"]
i = ["indium", "iridium", "iron"]
l = ["lanthanum", "lawrencium", "lead", "lithium", "lutetium"]
m = ["magnesium", "manganese", "mendelevium", "mercury", "molybdenum"]
n = ["neodymium", "neptunium", "nickel", "niobium", "nobelium"]
o = ["osmium"]
p = ["palladium", "platinum", "plutonium", "polonium", "potassium", "praseodymium", "promethium", "protactinium"]
q = ["quicksilver"]
r = ["radium", "rhenium", "rhodium", "rubidium", "ruthenium", "rutherfordium"]
s = ["samarium", "scandium", "seaborgium", "silicon", "silver", "sodium", "strontium"]
t = ["tantalum", "technetium", "tellurium", "terbium", "thallium", "thorium", "thulium", "tin", "titanium", "tungsten"]
u = ["uranium"]
v = ["vanadium"]
w = ["wolfram"]
y = ["ytterbium", "yttrium"]
z = ["zinc", "zirconium"]
