[adjectives]
a = ["abounding"]
c = ["condensed"]
n = ["negative", "normative"]
p = ["popular", "potent", "pretty"]
r = ["radioactive", "random", "reactive", "robust"]
s = ["silent", "silly", "stupid"]
t = ["tacit", "thrifty", "timeless"]
w = ["wiggly"]

[metals]
b = ["beryllium"]
d = ["duralim"]
f = ["fernico"]
i = ["iridium"]
p = ["palladium", "platinum"]
u = ["uranium"]
